### PR TITLE
Synchronizes submodules after checkout

### PR DESCRIPTION
**Pull request by bishtgautam**
Updates remote URL for all submodules after checkout.

### CODE REVIEW

**Comment by matthewhoffman** [comment]
That order looks correct to me - you need to re-sync the submodule(s) prior to updating it.  However, never having used `sync`, I'm not 100% sure if they are unintended consequences.  Note last paragraph in first answer here:
https://stackoverflow.com/questions/45678862/git-submodule-update-vs-git-submodule-sync
> Note also that, if you are making changes to the submodules, you might want the URLs to mismatch even if the upstream never changed them ... but using multiple remote URLs is probably a better idea for that case.

I could imagine for some submodule workflows where a developer does not have write access to the submodule being used, but they want to do some testing with their own fork, this change to the hook would prevent them from using any repo URL besides the one prescribed (I think).  Is this a concern for how any submodules are being used?

Personally, I think I would prefer to leave the `sync` command out of hooks, because it would prevent us from ever retiring old submodule repo URLs.  For instance, it would require that `ACME-Climate/MPAS` always exist even after everyone has moved over to entirely using `MPAS-Dev/MPAS-Release` - even though all the old MPAS commits from pre-v1 E3SM commits will be contained in `MPAS-Dev/MPAS-Release`, making it a perfectly workable submodule URL, if someone tried to checkout a pre-v1 commit of E3SM, this hook would force their clone to attempt to update MPAS from `ACME-Climate/MPAS`.



(BTW, this other link nicely described for me the difference between `.gitmodules` and `.git/config` and made submodules significantly less mysterious: https://stackoverflow.com/questions/33739376/git-submodule-sync-command-what-is-it-for  cc: @jonbob )

**Comment by rljacob** [comment]
The hooks are supposed to make things easier for the average E3SM developer/user.  Anyone who needs total control over submodules could just make a clone without the hooks.

**Comment by douglasjacobsen** [comment]
Not that it really matters to me, but when we created the hooks, they were intended to help catch common and expected issues that developers who were unfamiliar with git might have. Like committing to master. We put in the submodule update, because largely it doesn't do anything negative, but personally I'm with @matthewhoffman on this. It seems to me like the `git submodule sync` is a one time thing, since I'd expect any submodule URL you change to would be a super set of the previous submodule URL.

Since the new one is a super set of the old one, keeping the URL the same as it is in the newer commit doesn't hurt anything when moving back to old commits (i.e. `submodule update` would still work in that case).

But, to be fair, I haven't played with `submodule sync`. I'd recommend you guys make some test repos and see what happens. If `submodule sync` wipes your remotes and resets your .gitmodules file, I'd say that's going to be more pain than you guys will want to deal with. If it just resets the main remote in the submodule, but leaves any additional ones you have set up, then that should be fine.

Keep in mind, everyone who wants to make a change in MPAS will have to use the fork model, as that's what MPAS' workflow is currently. Unless you wanted to make a public ACME-Climate/MPAS-Release, and submit PRs from that, most E3SM developers won't have write access to MPAS-Dev/MPAS-Release (or whatever public repo is created). I don't know though, how the other models that are using submodules have their workflows defined.

**Comment by matthewhoffman** [comment]
My concerns with adding this are that 
1. it prevents us from being able to delete the old submodule URLs (e.g. ACME-Climate/MPAS), and I think having both in existence is likely to be more confusing than any one-time need for a user to manually run `git submodule sync`
2. I think it would be more confusing to have git silently changing what your submodules point to without you realizing it then having to possibly manually do this once.  Note than anyone who makes a fresh clone of v1 will be spared from this entire issue - it only affects people who continue to use a pre-v1 clone after v1, and then it is only a one-time fix. 
3. None of us (including me) have any real experience with git submodule sync, so we are speculating how it will operate in a hook (even though it seems straightforward).

Which leads me to a related question, is it anticipated that there will be some reason that new clones will be required after v1?  The obvious thing I can think of is if the "ACME" repository is renamed to "E3SM" (which seems like a good idea to me).  If so, then this whole submodule sync thing goes away (at least for now).

**Comment by rljacob** [comment]
We will be renaming the repo.  However by using github tools, old repo urls will still work.  This has been tested.

Yes I don't like things happening under the hood that get in the way either.  Lets close this.  But, Matt, I'd like you to write a paragraph in the Developers Guide about when/how one might need to change submodules.

**Comment by matthewhoffman** [comment]
@rljacob , sure, I can do that.  Glad to hear the directory is getting renamed.  After I wrote that, I realized github automatically forward renamed URLs, so what I said might not be true (we've been investigating these things as well for the move to open development in MPAS).  When you say, "github tools", is that what you are referring to, or something more complicated?

**Comment by rljacob** [comment]
I mean the "rename this repo" button and similar under "Settings" for a Github repo.

**Pull request closed without merging**
